# Generated by Django 2.2 on 2021-10-03 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('payment', models.CharField(blank=True, max_length=120, null=True)),
                ('coupon', models.CharField(blank=True, max_length=120, null=True)),
                ('being_delivered', models.CharField(blank=True, max_length=120, null=True)),
                ('received', models.CharField(blank=True, max_length=120, null=True)),
                ('refund_requested', models.CharField(blank=True, max_length=120, null=True)),
                ('refund_granted', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'orders',
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='TITLE')),
                ('digital', models.BooleanField(blank=True, default=False, null=True, verbose_name='DIGITAL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='PRODUCT IMAGE')),
                ('description', models.TextField(verbose_name='DESCRIPTION')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, verbose_name='PRICE')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, verbose_name='DISCOUNTED PRICE')),
                ('top_featured', models.BooleanField(blank=True, default=False, null=True, verbose_name='TOP FEATURE')),
                ('best_seller', models.BooleanField(blank=True, default=False, null=True, verbose_name='BEST SELLER')),
            ],
            options={
                'verbose_name_plural': 'products',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='ADDRESS')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='CITY')),
                ('state', models.CharField(blank=True, max_length=250, null=True, verbose_name='STATE')),
                ('zipcode', models.CharField(blank=True, max_length=250, null=True, verbose_name='ZIP CODE')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='DATE TIME')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order', verbose_name='ORDER')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USER')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=0, verbose_name='QUANTITY')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='DATE ADDED')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order', verbose_name='ORDER')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product', verbose_name='PRODUCT')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USER')),
            ],
            options={
                'verbose_name_plural': 'orderitems',
                'db_table': 'OrderItem',
            },
        ),
    ]
