# Generated by Django 2.2 on 2021-10-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderitem_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='best seller', verbose_name='DESCRIPTION'),
            preserve_default=False,
        ),
    ]
