# Generated by Django 3.2.4 on 2021-10-22 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pcshop.apps.web.store.models
import pcshop.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Admin. Email')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Account Email')),
                ('email3', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Branch Email')),
                ('email4', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Legal Email')),
                ('code', models.CharField(default=pcshop.core.utils.get_in_touch_randcode_gen, max_length=100, verbose_name='CODE')),
                ('fullname', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='DATE UPDATED')),
                ('time_updated', models.TimeField(blank=True, null=True, verbose_name='TIME UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('publish', models.DateField(blank=True, null=True)),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('code', models.CharField(default=pcshop.core.utils.order_randcode_gen, max_length=100, verbose_name='CODE')),
                ('transaction_id', models.CharField(blank=True, default=pcshop.core.utils.transaction_id_randcode_gen, max_length=120)),
                ('complete', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('payment', models.CharField(blank=True, max_length=120, null=True)),
                ('coupon', models.CharField(blank=True, max_length=120, null=True)),
                ('being_delivered', models.CharField(blank=True, max_length=120, null=True)),
                ('received', models.CharField(blank=True, max_length=120, null=True)),
                ('refund_requested', models.CharField(blank=True, max_length=120, null=True)),
                ('refund_granted', models.CharField(blank=True, max_length=120, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'orders',
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=pcshop.core.utils.product_randcode_gen, max_length=100, verbose_name='CODE')),
                ('name', models.CharField(max_length=250)),
                ('job_position', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to=pcshop.apps.web.store.models.upload_img_path, verbose_name='IMAGE')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='DATE UPDATED')),
                ('time_updated', models.TimeField(blank=True, null=True, verbose_name='TIME UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('publish', models.DateField(blank=True, null=True)),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('code', models.CharField(default=pcshop.core.utils.shipping_randcode_gen, max_length=100, verbose_name='CODE')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='ADDRESS')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='CITY')),
                ('state', models.CharField(blank=True, max_length=250, null=True, verbose_name='STATE')),
                ('zipcode', models.CharField(blank=True, max_length=250, null=True, verbose_name='ZIP CODE')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='DATE TIME')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USER')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='ORDER')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='DATE UPDATED')),
                ('time_updated', models.TimeField(blank=True, null=True, verbose_name='TIME UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('publish', models.DateField(blank=True, null=True)),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('code', models.CharField(default=pcshop.core.utils.product_randcode_gen, max_length=100, verbose_name='CODE')),
                ('title', models.CharField(max_length=120, verbose_name='TITLE')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='SLUG')),
                ('digital', models.BooleanField(blank=True, default=False, null=True, verbose_name='DIGITAL')),
                ('image', models.ImageField(blank=True, null=True, upload_to=pcshop.apps.web.store.models.upload_img_path, verbose_name='IMAGE')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='DESCRIPTION')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, verbose_name='PRICE')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, verbose_name='DISCOUNTED PRICE')),
                ('label', models.CharField(blank=True, choices=[('best', 'bestproduct')], max_length=250, null=True, verbose_name='LABEL')),
                ('top_featured', models.BooleanField(blank=True, default=False, null=True, verbose_name='TOP FEATURE')),
                ('best_seller', models.BooleanField(blank=True, default=False, null=True, verbose_name='BEST SELLER')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_categories', to='store.product')),
            ],
            options={
                'verbose_name_plural': 'products',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='DATE UPDATED')),
                ('time_updated', models.TimeField(blank=True, null=True, verbose_name='TIME UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('publish', models.DateField(blank=True, null=True)),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('code', models.CharField(default=pcshop.core.utils.orderitem_randcode_gen, max_length=100, verbose_name='CODE')),
                ('complete', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=0, verbose_name='QUANTITY')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USER')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='ORDER')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='PRODUCT')),
            ],
            options={
                'verbose_name_plural': 'orderitems',
                'db_table': 'OrderItem',
            },
        ),
    ]
