# Generated by Django 3.2.4 on 2021-10-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='all_product',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='BEST SELLER'),
        ),
    ]
