# Generated by Django 3.2.4 on 2021-10-07 18:44

from django.db import migrations, models
import pcshop.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Admin. Email')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Account Email')),
                ('email3', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Branch Email')),
                ('email4', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Legal Email')),
                ('code', models.CharField(default=pcshop.core.utils.get_in_touch_randcode_gen, max_length=100, verbose_name='CODE')),
                ('fullname', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
