# Generated by Django 3.2.4 on 2021-10-07 20:13

from django.db import migrations, models
import pcshop.apps.web.store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_getintouch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('job_position', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to=pcshop.apps.web.store.models.upload_img_path, verbose_name='IMAGE')),
            ],
        ),
    ]
